# Generated by Django 4.0.5 on 2022-08-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_is_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_plugged',
            field=models.BooleanField(default=False),
        ),
    ]
