# Generated by Django 4.0.5 on 2022-07-03 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beergame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('S', 'Started'), ('A', 'Active'), ('I', 'Inactive'), ('C', 'Completed'), ('X', 'Expired')], default='S', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='game',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL),
        ),
    ]
