# Generated by Django 4.0.5 on 2022-07-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beergame', '0008_game_last_play_by_game_next_play_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_play_at',
            field=models.DateTimeField(null=True),
        ),
    ]
