# Generated by Django 4.0.5 on 2022-07-10 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beergame', '0009_game_last_play_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameturn',
            old_name='player',
            new_name='game_player',
        ),
    ]
