# Generated by Django 4.0.5 on 2022-07-10 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beergame', '0010_rename_player_gameturn_game_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='last_play_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_plays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='next_play_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_plays', to=settings.AUTH_USER_MODEL),
        ),
    ]
