# Generated by Django 4.0.5 on 2022-07-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beergame', '0012_alter_game_last_play_at_alter_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('S', 'Started'), ('F', 'Finished'), ('T', 'Terminated')], default='C', max_length=1, verbose_name='Status'),
        ),
    ]
