# Generated by Django 4.0.5 on 2022-07-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beergame', '0013_alter_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameturn',
            name='round',
            field=models.IntegerField(default=0),
        ),
    ]
