# Generated by Django 4.0.5 on 2022-07-18 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beergame', '0017_alter_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='beergame.institution'),
        ),
    ]
