# Generated by Django 4.0.5 on 2022-07-21 04:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beergame', '0019_student'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('user', 'course')},
        ),
    ]
