# Generated by Django 4.0.5 on 2022-07-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beergame', '0022_alter_game_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turn_pointer',
            field=models.IntegerField(default=0),
        ),
    ]
